---
- name: Ping dari Juniper ke target
  hosts: JUNIPER
  gather_facts: no

  vars:
        # === INPUT SCHEMA FOR FRONTEND ===
    input_schema:
      - name: ping_dest
        label: "Ping Destination"
        type: "string"
        required: true
        placeholder: "8.8.8.8"
        description: "IP address or hostname to ping from Juniper device"

    # === EXECUTION VARIABLE ===
    ping_dest: "{{ ping_dest | mandatory }}"

  tasks:
    - name: Jalankan ping ke {{ ping_dest }}
      junipernetworks.junos.junos_command:
        commands:
          - "ping {{ ping_dest }} count 5"
      register: ping_result

    - name: Tampilkan hasil ping
      debug:
        var: ping_result.stdout_lines
